# Generated by Django 4.2.4 on 2023-08-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='career_interest',
            field=models.CharField(choices=[('Healthcare', 'Healthcare and Medicine'), ('Arts', 'Arts and Creativity'), ('Business', 'Business and Entrepreneurship'), ('Social_Sciences', 'Social Sciences'), ('Education', 'Education and Teaching'), ('Engineering', 'Engineering and Design'), ('Environmental', 'Environmental and Sustainability'), ('Communication', 'Communication and Media'), ('Culinary', 'Culinary and Hospitality'), ('Law', 'Law and Justice'), ('Sports', 'Sports and Fitness'), ('Technology', 'Technology and IT'), ('Trades', 'Skilled Trades'), ('Fashion', 'Fashion and Design'), ('Agriculture', 'Agriculture and Farming'), ('Writing', 'Writing and Publishing'), ('Research', 'Research and Academia'), ('Undecided', 'Undecided')], default='Undecided', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grade_level',
            field=models.CharField(choices=[(6, '6th'), (7, '7th'), (8, '8th'), (9, '9th (Freshman)'), (10, '10th (Sophomore)'), (11, '11th (Junior)'), (6, '12th (Senior)')], default=6, max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
